Fix compile error with gnu-efi 3.0.8
The commit 9485c65f6d28b71ff697849c1c8d47fd077ccd07 in gnu-efi 3.0.8
implements StrnCpy and StrnLen functions:

    commit 9485c65f6d28b71ff697849c1c8d47fd077ccd07
    Author: Peter Jones pjones@redhat.com
    Date: Tue Mar 13 15:20:28 2018 -0400

    gnu-efi: add some more common string functions.

    This adds bounded string helper functions:

    StrnLen()
    StrnCpy()
    StrnCat()
    StpnCpy()

    And the unbounded function StpCpy().

This would cause a seloader build error:

| /build/tmp-glibc/work/core2-64-wrs-linux/seloader/0.4.5+gitAUTOINC+9c2723afae-r0/recipe-sysroot/usr/lib64/libefi.a(str.o): In function StrnCpy': | /usr/src/debug/gnu-efi/3.0.8-r0/gnu-efi-3.0.8/lib/str.c:124: multiple definition of 'StrnCpy'
| /build/tmp-glibc/work/core2-64-wrs-linux/seloader/0.4.5+gitAUTOINC+9c2723afae-r0/git/Src/Efi/Lib/BaseLibrary/libBaseLibrary.a(StrnCpy.o):StrnCpy.c:(.text+0x0): first defined here
| /build/tmp-glibc/work/core2-64-wrs-linux/seloader/0.4.5+gitAUTOINC+9c2723afae-r0/git/Rules.mk:9: recipe for target 'SELoader.so' failed
| make[2]: *** [SELoader.so] Error 1

Bump the default GNU_EFI_VERSION to 308 and add conditional selection to
control the compilation. The user can specify GNU_EFI_VERSION=<ver>
explicitly if they want to build with old version gnu-efi.

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>